backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Home'
        name: 'Index Page'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - {
              label: Header,
              name: header,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - {
              label: Primary,
              name: primary,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Subheading, name: subheading, widget: string },
                  { label: Description, name: description, widget: string },
                ],
            }
          - {
              label: 'Details Grid',
              name: details,
              widget: object,
              fields:
                [
                  {
                    label: Details,
                    name: list,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: 'Call to Action',
              name: action,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  { label: Link, name: link, widget: string },
                ],
            }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
